repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: conda run isort .
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: conda run black .
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: conda run flake8 *.py
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: conda run mypy *.py
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: conda run pytest tests/
        types: [python]
