# Apply to all files without commiting:  pre-commit run --all-files
# Update this file: pre-commit autoupdate

exclude: '.git|.tox|.env|.gitignore'
default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: requirements-txt-fixer

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      args: [--ignore-missing-imports]
      exclude: docs/

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.7.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      exclude: docs/

- repo: https://github.com/asottile/pyupgrade
  rev: v2.10.0
  hooks:
    - id: pyupgrade
      args: [--py36-plus]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      additional_dependencies: [flake8-isort]
      exclude: docs/
